from random import seed
from random import randint

funfacts = {
  1: ["1 is the resin identification code used in recycling to identify polyethylene terephthalate", "lmao you got a 1 haha loser", "01 was the former dialing code for Greater London"],
  2: ["In pre-1972 Indonesian and Malay orthography, 2 was shorthand for the reduplication that forms plurals", "Two is the number of polynucleotide strands in a DNA double helix.", '2 is the ASCII code of "Start of Text".'],
  3: ["3 is the symbolic representation for Mu, Augustus Le Plongeon's and James Churchward's lost continent.", 'Three is considered a good number in Chinese culture because it sounds like the word "alive", compared to four, which sounds like the word "death"', "In Gaelic games (Gaelic football for men and women, hurling, and camogie), three points are awarded for a goal, scored when the ball passes underneath the crossbar and between the goal posts."],
  4: ["In Slavic mythology, the god Svetovid has four heads.", "In computing, four bits (half a byte) are sometimes called a nibble.", "In rowing, a four refers to a boat for four rowers, with or without coxswain."],
  5: ["In Hinduism, the god Shiva has five faces and his Mantra is also called Panchakshari (Five Worded) mantra.", "Towards the end of the film Monty Python and the Holy Grail (1975), the character of King Arthur repeatedly confuses the number five with the number three.", "In basketball, under the FIBA (used for all international play, and most non-US leagues) and NCAA women's rule sets, a team begins shooting bonus free throws once its opponent has committed five personal fouls in a quarter."],
  6: ['Sex- is a Latin prefix meaning "six" lmao.', "#6 is the pseudonym of American musician Shawn Crahan, when performing with the band Slipknot", "In Judaism, six symbolic foods placed on the Passover Seder Plate", "The Original Six teams in the National Hockey League are Toronto, Chicago, Montreal, New York, Boston, and Detroit. They are the oldest remaining teams in the league, though not necessarily the first six; they comprised the entire league from 1942 to 1967."],
  7: ["7 is the only number D for which the equation 2n − D = x2 has more than two solutions for n and x natural. In particular, the equation 2n − 7 = x2 is known as the Ramanujan–Nagell equation.", "999,999 divided by 7 is exactly 142,857. Therefore, when a vulgar fraction with 7 in the denominator is converted to a decimal expansion, the result has the same six-digit repeating sequence after the decimal point, but the sequence can start with any of those six digits. For example, 1/7 = 0.142857 142857... and 2/7 = 0.285714 285714....", "When rolling two standard six-sided dice, seven has a 6 in 62 (or 1/6) probability of being rolled (1–6, 6–1, 2–5, 5–2, 3–4, or 4–3), the greatest of any number."],
  8: ["In nuclear physics, 8 is the second magic number.", "Sea anemones of genus Edwardsia have eight mesenteries.", 'In Mahayana Buddhism, the branches of the Eightfold Path are embodied by the Eight Great Bodhisattvas: (Manjusri, Vajrapani, Avalokiteśvara, Maitreya, Ksitigarbha, Nivaranavishkambhi, Akasagarbha, and Samantabhadra). These are later (controversially) associated with the Eight Consciousnesses according to the Yogacara school of thought: consciousness in the five senses, thought-consciousness, self-consciousness, and unconsciousness-\"consciousness\" or \"store-house consciousness\" (alaya-vijñana). The \"irreversible\" state of enlightenment, at which point a Bodhisattva goes on \"autopilot\", is the Eight Ground or bhūmi. In general, \"eight\" seems to be an auspicious number for Buddhists, e.g., the \"eight auspicious symbols\" (the jewel-encrusted parasol; the goldfish (always shown as a pair, e.g., the glyph of Pisces); the self-replenishing amphora; the white kamala lotus-flower; the white conch; the eternal (Celtic-style, infinitely looping) knot; the banner of imperial victory; the eight-spoked wheel that guides the ship of state, or that symbolizes the Buddha\'s teaching). Similarly, Buddha\'s birthday falls on the 8th day of the 4th month of the Chinese calendar.'],
  9: ["The Ennead is a group of nine Egyptian deities, who, in some versions of the Osiris myth, judged whether Horus or Set should inherit Egypt.", "The 9 on Yahoo!, hosted by Maria Sansone, was a daily video compilation show, or vlog, on Yahoo! featuring the nine top \"web finds\" of the day.", "\"Revolution 9\", a sound collage which appears on The Beatles' eponymous 1968 album The Beatles (aka The White Album), prominently features a loop of a man's voice repeating the phrase \"Number nine\"."],
  10: ["The ESRB recommends video games with an E10+ rating to children aged 10 and up.", "In macOS, the F10 function key tiles all the windows of the current application and grays the windows of other applications.", "In Chinese astrology, the 10 Heavenly Stems, refer to a cyclic number system that is used also for time reckoning."],
  11: ["In the Babylonian creation myth Enûma Eliš the goddess Tiamat creates eleven monsters to take revenge for the death of her husband, Apsû.", "In most rugby league competitions (but not the Super League, which uses static squad numbering), one of the starting second-row forwards wears the number 11.", "Clocks depicted on Canadian currency, like the Canadian fifty-dollar bill, show 11:00."],
  12: ["In English Common Law, the tradition of twelve jurors harks back to the 10th-century law code introduced by Aethelred the Unready.", "The duodenum (from Latin duodecim, \"twelve\") is the first part of the small intestine, that is about twelve inches (30 cm) long. More precisely, this section of the intestine was measured not in inches but in fingerwidths. In fact, in German the name of the duodenum is Zwölffingerdarm and in Dutch the name is twaalfvingerige darm, both meaning \"twelve-finger bowel\".", "There are normally twelve pairs of ribs in the human body. Normally."],
  13: ["In triathlon, the number 13 is not used. As such, the numbering goes 11, 12, 14, 15 under the current numbering system.", "Many states in the U.S. allow girls as young as 13 to be married with written or verbal consent from their parent.", "In the Mayan Tzolk'in calendar, trecenas mark cycles of 13-day periods. The pyramids are also set up in 9 steps divided into 7 days and 6 nights, 13 days total."],
  14: ["14 is the number of Muqattaʿat in the Quran.", "14 is the minimum age at which one can view, rent, purchase, or buy tickets to an 18A rated movie with an accompanying adult in the Canadian provinces of the Maritimes and Manitoba.", "In golf, a player can have no more than 14 clubs in the bag."],
  15: ["The Hanbali Sunni madhab states that the age of fifteen of a solar or lunar calendar is when one's taklif (obligation or responsibility) begins and is the stage whereby one has his deeds recorded.", "15 is designated as an emergency number in Pakistan, for mobile phones, similar to the international GSM emergency number 112; if 112 is used in Pakistan, then the call is routed to 15. 112 can be used in an emergency even if the phone is locked and does not have a SIM card in it.", "In the UK a minor can be sent to prison to await trial at the age of 15."],
  16: ["In Spanish and Portuguese, 16 is the first compound number (Spanish: dieciséis, European Portuguese: dezasseis, Brazilian Portuguese: dezesseis); the numbers 11 (Spanish: once, Portuguese: onze) through 15 (Spanish: quince, Portuguese: quinze) have their own names.", "Sixteen is the age of majority in Cambodia, Cuba, Kyrgyzstan, and Vietnam.", "The metalcore band Demon Hunter has a song titled \"Sixteen\" on their Storm the Gates of Hell album"],
  17: ["In the US, 17 is the age at which one can enlist in the armed forces with parental consent", "Seventeen is a South Korean boy band consisting of 13 members divided into three sub-units, each with a different area of specialization: 'Hip-Hop Unit', 'Vocal Unit', and 'Performance Unit'.", "Detective Konawaka from the Paprika anime has a strong dislike for the number 17"],
  18: ["The Hebrew word for \"life\" is חי (chai), which has a numerical value of 18. Consequently, the custom has arisen in Jewish circles to give donations and monetary gifts in multiples of 18 as an expression of blessing for long life.", "In Nippon Professional Baseball (Japanese baseball), No.18 is known as Ace number.", "Eighteen Eighteen is a South African Rap artist."],
  19: ["19 years is very close to 235 lunations.", "19 is the atomic number of potassium. (Өте көркем!)", "Though the maximum score for a cribbage hand is 29, there is no combination of cards that adds up to 19 points. Many cribbage players, therefore, jokingly refer to a zero-point hand as \"a 19 hand.\""],
  20: ["Age 20 is the age at which Levites in the time of King David were allowed \"to do the work for the service of the house of the Lord\", the Temple in Jerusalem (see First Chronicles Chapter 23, verses 24 and 27). In the time of Ezra and Nehemiah, following the Babylonian captivity, it was Levites from the age of 20 upwards who were assigned \"to oversee the work of the house of the LORD\" (Ezra Chapter 3, verse 8).", "20 is the value of the letter J when computing the check digit in the serial number of an intermodal (shipping) container, as defined by ISO 6346.", "20 is the number of questions in the game Twenty Questions."],
  21: ["Duncan MacDougall reported that 21 grams is the weight of the soul, according to an experiment.", "There are 21 trump cards of the tarot deck if one does not consider The Fool to be a proper trump card.", "There are 21 solar rays in the flag of Kurdistan."],
  22: ["Traditional Tarot decks have 22 cards with allegorical subjects. These serve as trump cards in the game. The Fool is usually a kind of wild-card among the trumps and unnumbered, so the highest trump is numbered 21. Occult Tarot decks usually have 22 similar cards which are called Major Arcana by fortune-tellers. Occultists have related this number to the 22 letters of the Hebrew alphabet and the 22 paths in the Kabbalistic Tree of Life.", "There are 22 stars in the Paramount Pictures logo.", "In Jay-Z's song \"22 Two's\", he rhymes the words: too, to, and two, 22 times in the first verse."],
  23: ["23 skidoo (phrase) (sometimes 23 skiddoo) is an American slang phrase popularized during the early 20th century. 23 skidoo has been described as \"perhaps the first truly national fad expression and one of the most popular fad expressions to appear in the U.S\".", "23 is the number of times Julius Caesar was stabbed in the Theatre of Pompey.", "Nissan typically uses the number 23 for their Motorsport manufacturer teams, as the numbers 2 and 3 are pronounced \"ni\" and \"san\" in Japanese."],
  24: ["24 is the kissing number in 4-dimensional space: the maximum number of unit spheres that can all touch another unit sphere without overlapping. (The centers of 24 such spheres form the vertices of a 24-cell.)", "In Christian apocalyptic literature 24 represents the complete Church, being the sum of the 12 tribes of Israel and the 12 Apostles of the Lamb of God. For example, in The Book of Revelation: \"Surrounding the throne were twenty-four other thrones, and seated on them were twenty-four elders. They were dressed in white and had crowns of gold on their heads.\"", "24 is the number of spokes in the Ashok Chakra."],
  25: ["25 is the average percentage DNA overlap of an individual with their half-sibling, grandparent, grandchild, aunt, uncle, niece, nephew, identical twin cousin (offspring of identical twins), or double cousin.", "Pony is British slang for £25", "In baseball, the number 25 is typically reserved for the best slugger on the team. Examples include Mark McGwire, Barry Bonds, and Mark Teixeira."],
  26: ["26 is the number of spacetime dimensions in bosonic string theory.", "There are 26 holes in a floorball ball. Obviously.", "The expression \"For His mercy endures forever\" is found verbatim in English and the original Hebrew 26 times in Psalm 136. The expression is found once in each of the 26 verses."],
  27: ["Dark matter is thought to make up 27% of the universe\n                              @@@@@@@@@@@@@#\n                      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@&\n                 #@@@@@@@@@@@,              ./@@@@@@@@@@@,\n              @@@@@@@@                              @@@@@@@@@\n           @@@@@@&                                      &@@@@@@@\n        @@@@@@*                                            .@@@@@@%\n      .@@@@@                                                  #@@@@@\n     @@@@&                                                      &@@@@@\n    @@@@                                  &%                      /@@@@%\n   @@@(           #    (@@@@@@@@%      &@@@  .        @@@           @@@@&\n  @@@(          /@%@@@@@@@@@@@@@@(     @@@@@@@@@@@@@@@@@@@           &@@@/\n @@@@          (@@@@@@@@@@@@@@@@@*     @@@@@@@@@@@@@@@@@@@ @          @@@@\n @@@            @@@@@@@@   @@@@@@&     @@@@@@@@@  @@@@@@@@&           ,@@@@\n @@@              #@@@@@@,%@@@@@@       @@@@@@@.@@@@@@@@@              @@@@\n@@@@              ,&@@@@@@@@@@@@        &@@@@@@@@@@@@@@@               &@@@\n @@@               .@@@@@@@&(                #@@@@@@@@@@              ,@@@@\n @@@                                   *@@@(   *@@@@@@                @@@@@\n @@@                            @@@@@@@@@@@@@@                      @@@@@@@\n (@@@                        *@@@@@@@@@@@@@@@@@@@@.                @@@@@@@/\n  @@@@                @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@(@@@@@@@@@@\n   @@@&           %@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\n    @@@@        #@@@@@@@@@&       (@@@%,   .@@@@@@@@@@@@@@@@@@@@@@@@@@@@\n     ,@@@@,                      (@@@@@@@(     *@@@@@@@@@@@@@@@@@@@@@@@\n       @@@@@@@                 @@@@@@@@@@@@@(     @@@@@@@@@@@@@@@@@@@.\n         @@@@@@@%                    %@@@@@#       @@@@@@@@@@@@@@@@.\n           #@@@@@@@@#                      ,. .@@@@@@@@@@@@@@@@@@@\n              @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\n                 ,@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@/\n                      #@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@*\n                            (@@@@@@@@@@@@@@@@@@@(", "The type 27 vacuum tube (valve), a triode introduced in 1927, was the first tube mass-produced for commercial use to incorporate an indirectly heated cathode. This made it the first vacuum tube that could function as a detector in AC-powered radios. Prior to the introduction of the 27, home radios were powered by a set of three or more storage batteries with voltages of 3 volts to 135 volts.", "One of the anthropomorphic math symbols Lisa Simpson imagines talking to her in The Simpsons episode \"Girls Just Want to Have Sums\", which, instead of offering the expected pun-based aphorism, rather unhelpfully only says \"twenty seven\"."],
  28: ["The curing time of concrete is classically considered 28 days.", "28 is the common name for the parrot Barnardius zonarius semitorquatus, widely distributed in Western Australia and South Australia. Its call sounds like \"wenniate\".", "28 is the number of stab wounds in a murder case in the video game Detroit: Become Human. The phrase \"28 Stab Wounds\" spoken by a character in the game has become an Internet meme.", "In Quebec, François Pérusse, in one of his best-selling Album du peuple made a parody of Wheel of Fortune in which all of the letters picked by the contestant were present 28 times. As a result, 28 became an almost Mythical number used by many Quebec youths, the phrase \"Y\'en a 28\" (There are 28 [Letters]) became a running gag still used and recognized more than 15 years later."],
  29: ["29 is the number of Knuts in one Sickle in the fictional currency in the Harry Potter novels", "The Twenty-nine is often used in New Zealand for the missing miners and contractors believed to have been killed in the Pike River Mine disaster in November 2010.", "The Bishnois community follows 29 principles. Guru Jambheshwar had laid down 29 principles to be followed by the sect in 1485 A.D. In Hindi, Bish means 20 and noi means 9; thus, Bishnoi translates as Twenty-niners."],
  30: ["In the Christian Bible, at about age 30 (according to Luke 3:23), Jesus of Nazareth was baptized by John the Baptist, signaling the beginning of his public ministry of teaching and healing. It was also the age when David became King (2 Samuel 5:4) and Ezekiel and John the Baptist began their own ministries, (based on Ezekiel 1:1 and John the Baptist's age in comparison to Jesus.)", "One of the rallying-cries of the 1960s student/youth protest movement was the slogan, \'Don't trust anyone over thirty\'.", "In The Myth of Sisyphus the French existentialist Albert Camus comments that the age of thirty is a crucial period in the life of a man, for at that age he gains a new awareness of the meaning of time."],
  31: ["31 is the code for international direct-dial phone calls to the Netherlands", "There are 31 letters in the Macedonian alphabet.", "31 is the number of kings defeated by the incoming Israelite settlers in Canaan according to Joshua 12:24: \"all the kings, one and thirty\" (Wycliffe Bible translation)"],
  32: ["32 is the number of rays in the Japanese Rising Sun on the cover of Incubus' 2006 album Light Grenades", "32 is the number of pages in the average comic book (not including the cover)", "One of the central texts of the Pāli Canon in the Theravada Buddhist tradition, the Digha Nikaya, describes the appearance of the historical Buddha with a list of 32 physical characteristics."],
  33: ["33 is the ITU country code for the French telephone numbering plan area.", "A religious image of the Virgin Mary from the 18th century is known in Uruguay as \"Virgen de los Treinta y Tres\" (Virgin of the Thirty-Three); it was consecrated by Pope John Paul II in his visit to Uruguay in 1988.", "There are 33 degrees in Scottish Rite Freemasonry."],
  34: ["In The Count of Monte Cristo, Number 34 is how Edmond Dantès is referred to during his imprisonment in the Château d'If.", "\"#34\" is a song by the Dave Matthews Band", "34 is the traffic code of Istanbul, Turkey"],
  35: ["For Social Security in the United States, the 35 highest years of earnings are used to calculate retirement benefits.", "35 is a discrete semiprime (or biprime) (5 × 7); the tenth, and the first with 5 as the lowest non-unitary factor. The aliquot sum of 35 is 13 this being the second composite number with such an aliquot sum; the first being the cube 27. 35 is the last member of the first triple cluster of semiprimes 33, 34, 35. The second such triple discrete semiprime cluster is 85, 86, 87.", "35 is the minimum age of presidential candidates for election to Ireland, Russia, Trinidad and Tobago and Uruguay."],
  36: ["In the UK, a standard beer barrel is 36 UK gallons, about 163.7 litres.", "In one Māori legend, concerning the creation of mankind by the god Tāne, 36 gods took active part in assembling the various parts of the first human before Tāne breathed life into her.", "Australian basketball team the Adelaide 36ers is named after the year in which South Australia was founded."],
  37: ["+37 was the international dialing code of the German Democratic Republic (aka East Germany). Today the +37 prefix is shared by Lithuania (+370), Latvia (+371), Estonia (+372), Moldova (+373), Armenia (+374), Belarus (+375), Andorra (+376), Monaco (+377), San Marino (+378) and Vatican City (+379).", "37 is the number of seconds of church-bell and thunderstorm recording before the opening tritone riff in the song \"Black Sabbath\" on the album Black Sabbath by the band Black Sabbath, which is considered to mark the birth of heavy metal music.", "37 is the number of slots in European roulette (numbered 0 to 36, the 00 is not used in European roulette as it is in American roulette)"],
  38: ["The 38th parallel north is the pre-Korean War boundary between North Korea and South Korea.", "Bill C-38 legalized same-sex marriage in Canada.", "The 38 class is the most famous class of steam locomotive used in New South Wales."],
  39: ["In Afghanistan, the number 39 is considered unlucky, due to the belief that it is associated with pimps.", "39 was the duration, in nanoseconds, of the nuclear reaction in the largest nuclear explosion ever performed (Tsar Bomba)", "39 was the number of bodies found in a refrigerated articulated lorry in Grays, Essex, United Kingdom 2019"],
  40: ["Some Russians, Bulgarians, and Serbs believe that ghosts of the dead linger at the site of their death for forty days. After the forty days, additional prayers are performed at the grave (parastos (парастос) or panihida (панихида)), to escort the soul on its way to God's court.", "Crush 40 is an American-Japanese hard rock band featured in the Sonic the Hedgehog franchise produced by Sega and Sonic Team; their self-titled album is named after the band.", "Forty-shilling freeholders, a nickname, given to those who qualified for a franchise, the right to vote, based on their interest in land and/or property with an annual rental value of 40s. Introduced in England in 1430, it applied there and in many associated territories, in various forms, up to 1918."],
  41: ["41 is the precinct number that appears on the NYC police car in the film Ghostbusters during the earthquake moment of the film's climax.", "In Mexico \"cuarenta y uno\" (41) is slang referring to a homosexual. This is due to the 1901 arrest of 41 homosexuals at a hotel in Mexico City during the government of Porfirio Díaz (1876–1911).", "41 is the code number given to Tetsuo Shima by scientists in the manga and 1988 film Akira."],
  42: ["Tiling a plane using regular hexagons, which is honeycomb in appearance, is approximated in a topological sense to an accuracy of better than 1% using a stretcher bond brick pattern with bricks of 42 squares (6 by 7).", "In Final Fantasy: The Spirits Within, a 2001 computer-animated science fiction film, New York is Barrier City #42.", "42 Entertainment is the company responsible for several alternate reality games, including I Love Bees, Year Zero, and Why So Serious."],
  43: ["In The Big Bang Theory episode \"The 43 Peculiarity\", Howard and Raj try to solve the mystery of Sheldon disappearing every afternoon to a room with a chalkboard that has the number 43 written on it.", "\"43\" is a song by metal band Mushroomhead on the albums Mushroomhead and XX.", "43 is the name of a popular Spanish liqueur, Cuarenta y tres, which is distilled with 43 different herbs and spices."],
  44: ["44 is the name of a mysterious savior of Poland prophesied by the Polish national poet Adam Mickiewicz in his masterpiece dramatic poem Dziady (Forefathers): In scene 5 of act 3, the priest Piotr announces a \"reviver of the nation\" who is to bring back the lost freedom of Poland, and describes him with these words: Born from a foreign mother, his blood of ancient heroes, And his name will be forty and four.", "Number 44 (Russian: Номер 44) is the Russian localized title for a 2015 American-British mystery thriller film Child 44.", "An agent in the American television series Get Smart goes under the title of 44, usually assigned to small, enclosed, unexpected spots, to meet Maxwell Smart, agent 86."],
  45: ["Forty-five was a Big Finish 2008 audio play made for the 45th anniversary of the British science fiction television show Doctor Who.", "Issue 45 of The North Briton was thought to be seditious but its publisher, John Wilkes, was celebrated as a champion of liberty. The number 45 was used as a symbol of support for him. Banquets were held with a theme of 45 while many items were produced showing the number or featuring it in some way. For example, a wig was produced with 45 curls.", "45 was the number of the laps of the German Grand Prix from 1978 until 2001 (except 1985 because the race was held at Nürburgring)."],
  46: ["46 was the number of samurai, out of 47, who carried out the attack in the historical Ako vendetta; sometimes referred to as the 46 Ronins to discount the one samurai forced to turn back.", "46 is the number that unlocks the Destiny spaceship on the Sci-Fi TV show Stargate Universe. Dr. Rush discovers that the number 46 relates to the number of human chromosomes and begins sequencing different genetic codes to finally gain control of the ship's operating system. The episode was called \"Humans\".", "Because 46 in Japanese can be pronounced as \"yon roku\", and \"yoroshiku\"（よろしく） means \"my best regards\" in Japanese, people sometimes use 46 for greeting."],
  47: ["The Brooklyn-based hip hop collective Pro Era and its late co-founder Jamal Dewar, better known by his stage name Capital Steez, have made references to the number 47 in various songs by members of the group. The design of one of Pro Era's logos is the number 47 with its digits joined together. The origins of the group's connection with the number can be linked to the production of Capital Steez's 2012 debut mixtape AmeriKKKan Korruption. The rapper was heavily fixated with the number during that time; he felt that 47 was a perfect expression of balance in the world, representing the tension between the heart and the brain (the fourth and seventh chakra, respectively).", "After 47 years - 22 synodic periods of 780 days each - Mars returns to the same position among the stars and is in the same relationship to the Earth and Sun. The ancient Mesopotamians discovered this cycle.", "Its representation in binary being 00101111, 47 is a prime Thabit number, and as such is related to the pair of amicable numbers {17296, 18416}."],
  48: ["According to the Mishnah, Torah wisdom is acquired via 48 ways (Pirkei Avoth 6:6).", "On Tool’s album Ænima, there is a song named \"Forty-Six & 2\"; the sum of which is 48.", "48 is the number of mountain peaks in New Hampshire over 4000 feet above sea level, as defined by the Appalachian Mountain Club."],
  49: ["In Buddhism, 49 days is one of the lengths of the intermediate state (bardo)", "In Blues music lore, it was at the junction of US Highway 49 and 61 in Clarksdale, Mississippi, that legendary bluesman Robert Johnson sold his soul to the devil in return for fame and success. In later years Howlin' Wolf immortalized the road in the song “Highway 49”, originally written by Big Joe Williams.","A 49 is a party after a powwow or any gathering of American Indians, held by the participants. It is also type of song that is sung on such occasions. A 49 is typically held in an isolated place and features drumming and singing."],
  50: ["In Kabbalah, there are 50 Gates of Wisdom (or Understanding) and 50 Gates of Impurity", "In cricket one day internationals, each side may bat for 50 overs.", "The Christian Feast of Pentecost takes place on the 50th day of the Easter Season"],
  51: ["51 is the number of the laps of the Azerbaijan Grand Prix.", "In the 2006 film Cars, 51 was Doc Hudson's number.", "51 is the code for international direct dial phone calls to Peru"],
  52: ["52 American hostages were held in the Iran hostage crisis.", "The number of the laps of the British Grand Prix since 2010.", "53 is a significant number in the Maya calendar"],
  53: ["In How the Grinch Stole Christmas!, and its animated TV special the Grinch says he's put up with the Whos' Christmas cheer for 53 years.", "53 More Things To Do In Zero Gravity is a book mentioned in The Hitchhiker's Guide to the Galaxy", "53 is the smallest prime number that does not divide the order of any sporadic group."],
  54: ["A score of 54 in golf is colloquially referred to as a perfect round. This score has never been achieved in competition.", "54 is the number used when a player is defeated 3 games in a row in racquetball.", "Six by nine (54) is the incorrect Answer to the Ultimate Question of Life, the Universe, and Everything"],
  55: ["55 is the name of a song by Kasabian. The song was released as a B side to Club Foot and was recorded live when the band performed at London's Brixton Academy.", "55 is the number of the laps of the Abu Dhabi Grand Prix.", "Agitation and Propaganda against the State, also known as Constitution law 55 was a law during Communist Albania."],
  56: ["In humans, olfactory receptors are categorized in 56 families.", "Roberto, a character in Futurama, gets angered when Bender chooses the number \"56-ish\" when negotiating to spare his friends", "Shirley Temple, as a child, wore 56 curls in her hair. Curls were set by her mother, who thus made sure of the exact number."],
  57: ["In Rudyard Kipling's short story \"The Man Who Would Be King\", the character Peachy states: \"This business is our Fifty-Seven\" after he and Daniel are discovered to be men, not gods. This alludes to the Indian Rebellion in 1857, or India's First War of Independence, against British Rule.", "In the game Hollow Knight, a character named Zote the Mighty has fifty-seven precepts, all of which offer rather humorous, lackluster, or completely bad advice to the player", "B'hrian Bloodaxe, the first Low King of the dwarfs, killed fifty-seven trolls in the legendary Battle of Koom Valley on Discworld (a fictional world created by author Terry Pratchett)"],
  58: ["Belief in the existence of 58 original sins by several civilizations native to Central America or South America caused the number to symbolize misfortune. Aztec oracles supposedly stumbled across the number an unnaturally high number of times before disaster fell. One famous recording of this, though largely discredited as mere folktale, concerned the oracle of Moctezuma II, who allegedly counted 58 pieces of gold scattered before a sacrificial pit the day prior to the arrival of Hernán Cortés.", "In the popular TV show SpongeBob SquarePants, Patrick claims that \"58 is like the luckiest number ever.\"", "On the PGA Tour, 58 is the lowest score in an 18-hole round, achieved by Jim Furyk in the final round of the 2016 Travelers Championship at TPC River Highlands."],
  59: ["59 is the number of beads on a Roman Catholic rosary (Dominican).", "59 was the number on a button commonly worn by feminist activists in the 1970s; this was based on the claim that a woman earned 59 cents to an equally qualified man's dollar", "Beethoven's Opus 59 consists of the three so-called Razumovsky Quartets"],
  60: ["The Babylonian cuneiform numerals had a base of 60, inherited from the Sumerian and Akkadian civilizations, and possibly motivated by the large number of divisors that 60 has. The sexagesimal measurement of time and of geometric angles is a legacy of the Babylonian system.", "In darts, 60 (treble-twenty) is the highest score that can be achieved with a single dart.", "60 occurs several times in the Bible; for example, as the age of Isaac when Jacob and Esau were born, and the number of warriors escorting King Solomon."],
  61: ["Rotation, a variation of pool, is sometimes called 61.", "The number of Citadel cadets on The Summerall Guards.", "The maximum number of tables that can be joined in a single MariaDB or MySQL query."],
  62: ["In the 1998 Home Run Race, Mark McGwire hit his 62nd home run on September 8, breaking the single-season record. Sammy Sosa hit his 62nd home run just days later on September 13.", "62 is the number of faces of two of the Archimedean solids, the rhombicosidodecahedron and truncated icosidodecahedron.", "62 is the code for international direct dial calls to Indonesia."],
  63: ["63 is a card game, popular in Carleton County, New Brunswick", "63 is the number of chromosomes found in the offspring of a donkey and a horse", "There are 63 Salakapurusas (great beings) in Jain cosmology."],
  64: ["64 is a slang term referring to a 1964 Chevrolet Impala, often configured as a lowrider, a popular subject among early-1990s gangsta rap.", "64 is the number of golden disks in the myth of the Tower of Hanoi", "Number of hexagrams in the I Ching"],
  65: ["65 is commonly used in names of many dishes of South India cuisine, for instance Chicken 65.", "The setting of the American classic TV series Naked City (1958–63) was the 65th Precinct in New York City (sometimes referred to as simply \"the 65\").", "65 is a commonly used abbreviation for the Sheffield, UK, post-rock band 65daysofstatic."],
  66: ["66 is the number of verses in Chapter 3 of the Book of Lamentations in the Old Testament.", "In the Star Wars movie series, Order 66 is a prepared order to the clone troopers to kill the Jedi commanding them.", "In the video game Fullmetal Alchemist, elusive villain Barry the Chopper is imprisoned in cell number 66, which later becomes his alias when battling the brothers at Laboratory Five."],
  67: ["67 is the province/traffic code of Zonguldak Province in Turkey.", "Pekka Koskela skated the 1000 metres in 1:07:00 (67 seconds) on 10 November 2007, a world record at the time.", "The number of the laps of the German Grand Prix since 2002 if the race was held at Hockenheimring."],
  68: ["In the restaurant industry, 68 may be used as a code meaning \"put back on the menu\", being the opposite of 86 which means \"remove from the menu\".", "68 is the largest known number to be the sum of two primes in exactly two different ways: 68 = 7 + 61 = 31 + 37. All higher even numbers that have been checked are the sum of three or more pairs of primes; the conjecture that 68 is the largest number with this property is closely related to the Goldbach conjecture and, like it, remains unproven.", "On an infinite chessboard, there are 68 squares three knight's moves away from any cell."],
  69: ["lmao the sex number", "In reference to the sex position, \"69\" has become an internet meme, where users will respond to any occurrence of the number with the word \"nice\" and draw specific attention to it. This means to sarcastically imply that the reference to the sex position was intentional. Because of its association with the sex position and resulting meme, \"69\" has become known as \"the sex number\" in these communities.", "69 was the last possible television channel number in the UHF bandplan for American terrestrial television from 1982 until its withdrawal on December 31, 2011."],
  70: ["In Matthew 18:21–22, Jesus tells Peter to forgive people seventy times seven times.", "In the Far Eastern culture of China, Japan, Korea, etc., 70 years old is called the Rare Age of the Olden Times (古稀 Guxi in Chinese, 古稀 Koki in Japanese, 고희 Gohui in Korean, etc.), as written in one of Du Fu's poems.", "The French Languaguage does not have a specific word for 70. The French word for 70 is soixante-dix \"sixty-ten\". (This is true only in France; other French-speaking regions such as Belgium, Switzerland, Aosta Valley and Jersey use septante.)"],
  # 420: ["the weed number", "420 is the country calling code for Czech Republic.", "lmao its the weed number"],
  # 666: ["ooooh spooky", "Using gematria, Neron Caesar transliterated from Greek into Hebrew produces the number 666. The Latin spelling of \"Nero Caesar\" transliterated into Hebrew produces the number 616. Thus, in the Bible, 666 may have been a coded reference to Nero, the Roman Emperor from 55 to 68 AD.", "666 was a winning lottery number in the 1980 Pennsylvania Lottery scandal, in which equipment was tampered to favor a 4 or 6 as each of the three individual random digits."],
}
seed()

randfact = randint(0, 2)

keys = len(funfacts.keys())

randnumber = randint(1, keys)

facts = funfacts[randnumber]

print(randnumber)
print(facts[randfact])