from random import seed
from random import randint

funfacts = {
  1: ["1 is the resin identification code used in recycling to identify polyethylene terephthalate", "lmao you got a 1 haha loser", "01 was the former dialing code for Greater London"],
  2: ["In pre-1972 Indonesian and Malay orthography, 2 was shorthand for the reduplication that forms plurals", "Two is the number of polynucleotide strands in a DNA double helix.", '2 is the ASCII code of "Start of Text".'],
  3: ["3 is the symbolic representation for Mu, Augustus Le Plongeon's and James Churchward's lost continent.", 'Three is considered a good number in Chinese culture because it sounds like the word "alive", compared to four, which sounds like the word "death"', "In Gaelic games (Gaelic football for men and women, hurling, and camogie), three points are awarded for a goal, scored when the ball passes underneath the crossbar and between the goal posts."],
  4: ["In Slavic mythology, the god Svetovid has four heads.", "In computing, four bits (half a byte) are sometimes called a nibble.", "In rowing, a four refers to a boat for four rowers, with or without coxswain."],
  5: ["In Hinduism, the god Shiva has five faces and his Mantra is also called Panchakshari (Five Worded) mantra.", "Towards the end of the film Monty Python and the Holy Grail (1975), the character of King Arthur repeatedly confuses the number five with the number three.", "In basketball, under the FIBA (used for all international play, and most non-US leagues) and NCAA women's rule sets, a team begins shooting bonus free throws once its opponent has committed five personal fouls in a quarter."],
  6: ['Sex- is a Latin prefix meaning "six" lmao.', "#6 is the pseudonym of American musician Shawn Crahan, when performing with the band Slipknot", "In Judaism, six symbolic foods placed on the Passover Seder Plate", "The Original Six teams in the National Hockey League are Toronto, Chicago, Montreal, New York, Boston, and Detroit. They are the oldest remaining teams in the league, though not necessarily the first six; they comprised the entire league from 1942 to 1967."],
  7: ["7 is the only number D for which the equation 2n − D = x2 has more than two solutions for n and x natural. In particular, the equation 2n − 7 = x2 is known as the Ramanujan–Nagell equation.", "999,999 divided by 7 is exactly 142,857. Therefore, when a vulgar fraction with 7 in the denominator is converted to a decimal expansion, the result has the same six-digit repeating sequence after the decimal point, but the sequence can start with any of those six digits. For example, 1/7 = 0.142857 142857... and 2/7 = 0.285714 285714....", "When rolling two standard six-sided dice, seven has a 6 in 62 (or 1/6) probability of being rolled (1–6, 6–1, 2–5, 5–2, 3–4, or 4–3), the greatest of any number."],
  8: ["In nuclear physics, 8 is the second magic number.", "Sea anemones of genus Edwardsia have eight mesenteries.", 'In Mahayana Buddhism, the branches of the Eightfold Path are embodied by the Eight Great Bodhisattvas: (Manjusri, Vajrapani, Avalokiteśvara, Maitreya, Ksitigarbha, Nivaranavishkambhi, Akasagarbha, and Samantabhadra). These are later (controversially) associated with the Eight Consciousnesses according to the Yogacara school of thought: consciousness in the five senses, thought-consciousness, self-consciousness, and unconsciousness-\"consciousness\" or \"store-house consciousness\" (alaya-vijñana). The \"irreversible\" state of enlightenment, at which point a Bodhisattva goes on \"autopilot\", is the Eight Ground or bhūmi. In general, \"eight\" seems to be an auspicious number for Buddhists, e.g., the \"eight auspicious symbols\" (the jewel-encrusted parasol; the goldfish (always shown as a pair, e.g., the glyph of Pisces); the self-replenishing amphora; the white kamala lotus-flower; the white conch; the eternal (Celtic-style, infinitely looping) knot; the banner of imperial victory; the eight-spoked wheel that guides the ship of state, or that symbolizes the Buddha\'s teaching). Similarly, Buddha\'s birthday falls on the 8th day of the 4th month of the Chinese calendar.'],
  9: ["The Ennead is a group of nine Egyptian deities, who, in some versions of the Osiris myth, judged whether Horus or Set should inherit Egypt.", "The 9 on Yahoo!, hosted by Maria Sansone, was a daily video compilation show, or vlog, on Yahoo! featuring the nine top \"web finds\" of the day.", "\"Revolution 9\", a sound collage which appears on The Beatles' eponymous 1968 album The Beatles (aka The White Album), prominently features a loop of a man's voice repeating the phrase \"Number nine\"."],
  10: ["The ESRB recommends video games with an E10+ rating to children aged 10 and up.", "In macOS, the F10 function key tiles all the windows of the current application and grays the windows of other applications.", "In Chinese astrology, the 10 Heavenly Stems, refer to a cyclic number system that is used also for time reckoning."],
  11: ["In the Babylonian creation myth Enûma Eliš the goddess Tiamat creates eleven monsters to take revenge for the death of her husband, Apsû.", "In most rugby league competitions (but not the Super League, which uses static squad numbering), one of the starting second-row forwards wears the number 11.", "Clocks depicted on Canadian currency, like the Canadian fifty-dollar bill, show 11:00."],
  12: ["In English Common Law, the tradition of twelve jurors harks back to the 10th-century law code introduced by Aethelred the Unready.", "The duodenum (from Latin duodecim, \"twelve\") is the first part of the small intestine, that is about twelve inches (30 cm) long. More precisely, this section of the intestine was measured not in inches but in fingerwidths. In fact, in German the name of the duodenum is Zwölffingerdarm and in Dutch the name is twaalfvingerige darm, both meaning \"twelve-finger bowel\".", "There are normally twelve pairs of ribs in the human body. Normally."],
  13: ["In triathlon, the number 13 is not used. As such, the numbering goes 11, 12, 14, 15 under the current numbering system.", "Many states in the U.S. allow girls as young as 13 to be married with written or verbal consent from their parent.", "In the Mayan Tzolk'in calendar, trecenas mark cycles of 13-day periods. The pyramids are also set up in 9 steps divided into 7 days and 6 nights, 13 days total."],
  14: ["14 is the number of Muqattaʿat in the Quran.", "14 is the minimum age at which one can view, rent, purchase, or buy tickets to an 18A rated movie with an accompanying adult in the Canadian provinces of the Maritimes and Manitoba.", "In golf, a player can have no more than 14 clubs in the bag."],
  15: ["The Hanbali Sunni madhab states that the age of fifteen of a solar or lunar calendar is when one's taklif (obligation or responsibility) begins and is the stage whereby one has his deeds recorded.", "15 is designated as an emergency number in Pakistan, for mobile phones, similar to the international GSM emergency number 112; if 112 is used in Pakistan, then the call is routed to 15. 112 can be used in an emergency even if the phone is locked and does not have a SIM card in it.", "In the UK a minor can be sent to prison to await trial at the age of 15."],
  16: ["In Spanish and Portuguese, 16 is the first compound number (Spanish: dieciséis, European Portuguese: dezasseis, Brazilian Portuguese: dezesseis); the numbers 11 (Spanish: once, Portuguese: onze) through 15 (Spanish: quince, Portuguese: quinze) have their own names.", "Sixteen is the age of majority in Cambodia, Cuba, Kyrgyzstan, and Vietnam.", "The metalcore band Demon Hunter has a song titled \"Sixteen\" on their Storm the Gates of Hell album"],
  17: ["In the US, 17 is the age at which one can enlist in the armed forces with parental consent", "Seventeen is a South Korean boy band consisting of 13 members divided into three sub-units, each with a different area of specialization: 'Hip-Hop Unit', 'Vocal Unit', and 'Performance Unit'.", "Detective Konawaka from the Paprika anime has a strong dislike for the number 17"],
  18: ["The Hebrew word for \"life\" is חי (chai), which has a numerical value of 18. Consequently, the custom has arisen in Jewish circles to give donations and monetary gifts in multiples of 18 as an expression of blessing for long life.", "In Nippon Professional Baseball (Japanese baseball), No.18 is known as Ace number.", "Eighteen Eighteen is a South African Rap artist."],
  19: ["19 years is very close to 235 lunations", "19 is the atomic number of potassium. (Өте көркем!)", "Though the maximum score for a cribbage hand is 29, there is no combination of cards that adds up to 19 points. Many cribbage players, therefore, jokingly refer to a zero-point hand as \"a 19 hand.\""],
  20: ["Age 20 is the age at which Levites in the time of King David were allowed \"to do the work for the service of the house of the Lord\", the Temple in Jerusalem (see First Chronicles Chapter 23, verses 24 and 27). In the time of Ezra and Nehemiah, following the Babylonian captivity, it was Levites from the age of 20 upwards who were assigned \"to oversee the work of the house of the LORD\" (Ezra Chapter 3, verse 8).", "20 is the value of the letter J when computing the check digit in the serial number of an intermodal (shipping) container, as defined by ISO 6346.", "20 is the number of questions in the game Twenty Questions."],
  21: ["Duncan MacDougall reported that 21 grams is the weight of the soul, according to an experiment.", "There are 21 trump cards of the tarot deck if one does not consider The Fool to be a proper trump card.", "There are 21 solar rays in the flag of Kurdistan."],
  22: ["Traditional Tarot decks have 22 cards with allegorical subjects. These serve as trump cards in the game. The Fool is usually a kind of wild-card among the trumps and unnumbered, so the highest trump is numbered 21. Occult Tarot decks usually have 22 similar cards which are called Major Arcana by fortune-tellers. Occultists have related this number to the 22 letters of the Hebrew alphabet and the 22 paths in the Kabbalistic Tree of Life.", "There are 22 stars in the Paramount Pictures logo.", "In Jay-Z's song \"22 Two's\", he rhymes the words: too, to, and two, 22 times in the first verse."],
  23: ["23 skidoo (phrase) (sometimes 23 skiddoo) is an American slang phrase popularized during the early 20th century. 23 skidoo has been described as \"perhaps the first truly national fad expression and one of the most popular fad expressions to appear in the U.S\".", "23 is the number of times Julius Caesar was stabbed in the Theatre of Pompey.", "Nissan typically uses the number 23 for their Motorsport manufacturer teams, as the numbers 2 and 3 are pronounced \"ni\" and \"san\" in Japanese."],
  24: ["24 is the kissing number in 4-dimensional space: the maximum number of unit spheres that can all touch another unit sphere without overlapping. (The centers of 24 such spheres form the vertices of a 24-cell.)", "In Christian apocalyptic literature 24 represents the complete Church, being the sum of the 12 tribes of Israel and the 12 Apostles of the Lamb of God. For example, in The Book of Revelation: \"Surrounding the throne were twenty-four other thrones, and seated on them were twenty-four elders. They were dressed in white and had crowns of gold on their heads.\"", "24 is the number of spokes in the Ashok Chakra."],
  25: ["25 is the average percentage DNA overlap of an individual with their half-sibling, grandparent, grandchild, aunt, uncle, niece, nephew, identical twin cousin (offspring of identical twins), or double cousin.", "Pony is British slang for £25", "In baseball, the number 25 is typically reserved for the best slugger on the team. Examples include Mark McGwire, Barry Bonds, and Mark Teixeira."],
  26: ["26 is the number of spacetime dimensions in bosonic string theory.", "There are 26 holes in a floorball ball. Obviously.", "The expression \"For His mercy endures forever\" is found verbatim in English and the original Hebrew 26 times in Psalm 136. The expression is found once in each of the 26 verses."],
  27: ["Dark matter is thought to make up 27% of the universe\n                              @@@@@@@@@@@@@#\n                      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@&\n                 #@@@@@@@@@@@,              ./@@@@@@@@@@@,\n              @@@@@@@@                              @@@@@@@@@\n           @@@@@@&                                      &@@@@@@@\n        @@@@@@*                                            .@@@@@@%\n      .@@@@@                                                  #@@@@@\n     @@@@&                                                      &@@@@@\n    @@@@                                  &%                      /@@@@%\n   @@@(           #    (@@@@@@@@%      &@@@  .        @@@           @@@@&\n  @@@(          /@%@@@@@@@@@@@@@@(     @@@@@@@@@@@@@@@@@@@           &@@@/\n @@@@          (@@@@@@@@@@@@@@@@@*     @@@@@@@@@@@@@@@@@@@ @          @@@@\n @@@            @@@@@@@@   @@@@@@&     @@@@@@@@@  @@@@@@@@&           ,@@@@\n @@@              #@@@@@@,%@@@@@@       @@@@@@@.@@@@@@@@@              @@@@\n@@@@              ,&@@@@@@@@@@@@        &@@@@@@@@@@@@@@@               &@@@\n @@@               .@@@@@@@&(                #@@@@@@@@@@              ,@@@@\n @@@                                   *@@@(   *@@@@@@                @@@@@\n @@@                            @@@@@@@@@@@@@@                      @@@@@@@\n (@@@                        *@@@@@@@@@@@@@@@@@@@@.                @@@@@@@/\n  @@@@                @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@(@@@@@@@@@@\n   @@@&           %@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\n    @@@@        #@@@@@@@@@&       (@@@%,   .@@@@@@@@@@@@@@@@@@@@@@@@@@@@\n     ,@@@@,                      (@@@@@@@(     *@@@@@@@@@@@@@@@@@@@@@@@\n       @@@@@@@                 @@@@@@@@@@@@@(     @@@@@@@@@@@@@@@@@@@.\n         @@@@@@@%                    %@@@@@#       @@@@@@@@@@@@@@@@.\n           #@@@@@@@@#                      ,. .@@@@@@@@@@@@@@@@@@@\n              @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\n                 ,@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@/\n                      #@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@*\n                            (@@@@@@@@@@@@@@@@@@@(", "The type 27 vacuum tube (valve), a triode introduced in 1927, was the first tube mass-produced for commercial use to incorporate an indirectly heated cathode. This made it the first vacuum tube that could function as a detector in AC-powered radios. Prior to the introduction of the 27, home radios were powered by a set of three or more storage batteries with voltages of 3 volts to 135 volts.", "One of the anthropomorphic math symbols Lisa Simpson imagines talking to her in The Simpsons episode \"Girls Just Want to Have Sums\", which, instead of offering the expected pun-based aphorism, rather unhelpfully only says \"twenty seven\"."],
  28: ["The curing time of concrete is classically considered 28 days.", "28 is the common name for the parrot Barnardius zonarius semitorquatus, widely distributed in Western Australia and South Australia. Its call sounds like \"wenniate\".", "28 is the number of stab wounds in a murder case in the video game Detroit: Become Human. The phrase \"28 Stab Wounds\" spoken by a character in the game has become an Internet meme.", "In Quebec, François Pérusse, in one of his best-selling Album du peuple made a parody of Wheel of Fortune in which all of the letters picked by the contestant were present 28 times. As a result, 28 became an almost Mythical number used by many Quebec youths, the phrase \"Y\'en a 28\" (There are 28 [Letters]) became a running gag still used and recognized more than 15 years later."],
  29: ["29 is the number of Knuts in one Sickle in the fictional currency in the Harry Potter novels", "The Twenty-nine is often used in New Zealand for the missing miners and contractors believed to have been killed in the Pike River Mine disaster in November 2010.", "The Bishnois community follows 29 principles. Guru Jambheshwar had laid down 29 principles to be followed by the sect in 1485 A.D. In Hindi, Bish means 20 and noi means 9; thus, Bishnoi translates as Twenty-niners."],
  30: ["In the Christian Bible, at about age 30 (according to Luke 3:23), Jesus of Nazareth was baptized by John the Baptist, signaling the beginning of his public ministry of teaching and healing. It was also the age when David became King (2 Samuel 5:4) and Ezekiel and John the Baptist began their own ministries, (based on Ezekiel 1:1 and John the Baptist's age in comparison to Jesus.)", "One of the rallying-cries of the 1960s student/youth protest movement was the slogan, \'Don't trust anyone over thirty\'.", "In The Myth of Sisyphus the French existentialist Albert Camus comments that the age of thirty is a crucial period in the life of a man, for at that age he gains a new awareness of the meaning of time."],
  # 69: ["lmao the sex number", "In reference to the sex position, \"69\" has become an internet meme, where users will respond to any occurrence of the number with the word \"nice\" and draw specific attention to it. This means to sarcastically imply that the reference to the sex position was intentional. Because of its association with the sex position and resulting meme, \"69\" has become known as \"the sex number\" in these communities.", "69 was the last possible television channel number in the UHF bandplan for American terrestrial television from 1982 until its withdrawal on December 31, 2011."],
  # 420: ["the weed number", "420 is the country calling code for Czech Republic.", "lmao its the weed number"],
  # 666: ["ooooh spooky", "Using gematria, Neron Caesar transliterated from Greek into Hebrew produces the number 666. The Latin spelling of \"Nero Caesar\" transliterated into Hebrew produces the number 616. Thus, in the Bible, 666 may have been a coded reference to Nero, the Roman Emperor from 55 to 68 AD.", "666 was a winning lottery number in the 1980 Pennsylvania Lottery scandal, in which equipment was tampered to favor a 4 or 6 as each of the three individual random digits."],
}
seed()

randfact = randint(0, 2)

keys = len(funfacts.keys())

randnumber = randint(1, keys)

facts = funfacts[randnumber]

print(randnumber)
print(facts[randfact])